Update wesnoth-units.po
hrubymar10/wesnoth-cs pull request #14
Opened 2020-10-09 12:02 UTC by MultiSeptim

ke commit 1b7eb4f

2020-10-09 21:51 UTC, celerini requested changes
už se mi to špatně čte, možná, že až to opravíte, tak ještě něco najdu

2020-10-09 21:51 UTC, celerini commented on wesnoth-units.po
> +"účely mnoho různých plemen. Koně, používaní na těžkou práci, jsou chováni "
trochu jsem se ponořil do opravy pádu, abych se vynořil blíže originálu

ohledně čárek bych řekl, že se jedná o těsný přívlastek

```suggestion
"Pouštní lidé jsou proslavení chovatelé koní, kteří chovají mnoho různých "
"plemen pro nejrůznější účely. Koně používaní na těžkou práci jsou chováni "
```

2020-10-09 21:51 UTC, celerini commented on wesnoth-units.po
> +"pro sílu, zatímco ti, kteří jsou používaní cestách či v karavanách, jsou "
ještě oprava trpného rodu

```suggestion
"pro sílu, zatímco ti, kteří jsou používáni na cestách či v karavanách, jsou "
```

2020-10-09 21:51 UTC, celerini commented on wesnoth-units.po
> +"linie. Klíčovým rysem, co těmto jezdcům umožňuje být tak efektivní a "
```suggestion
"linie. Klíčovým rysem, který těmto jezdcům umožňuje být tak efektivní a "
```

2020-10-09 21:51 UTC, celerini commented on wesnoth-units.po
> +"všestranní na sypkých dunách, je manévrovatelnost."
jednodušší?
```suggestion
"všestranní na sypkých dunách, je ovladatelnost."
```

2020-10-09 21:51 UTC, celerini commented on wesnoth-units.po
> +"obzvláště vhodné pro skřeti s malým vzrůstem nebo slabší tělesnou "
```suggestion
"obzvláště vhodné pro skřety s malým vzrůstem nebo slabší tělesnou "
```

2020-10-09 21:51 UTC, celerini commented on wesnoth-units.po
> +"silnějších druhů. I když jsou obvykle tito skřeti jen špatnou vyzbrojeni a "
```suggestion
"silnějších druhů. I když jsou obvykle tito skřeti jen špatně vyzbrojeni a "
```

2020-10-09 22:24 UTC, MultiSeptim commented on wesnoth-units.po
> +"účely mnoho různých plemen. Koně, používaní na těžkou práci, jsou chováni "
Ten přívlastek je dost soda, oceňuji.

2020-10-09 22:26 UTC, MultiSeptim commented on wesnoth-units.po
> +"linie. Klíčovým rysem, co těmto jezdcům umožňuje být tak efektivní a "
Lavíroval jsem mezi který a co a to co mi líp znělo. Ale je to asi jedno.

2020-10-09 22:27 UTC, MultiSeptim commented on wesnoth-units.po
> +"všestranní na sypkých dunách, je manévrovatelnost."
Ovladatelnost by se týkala koní, ne jezdců.

2020-10-09 22:28 UTC, MultiSeptim commented on wesnoth-units.po
> +"pro sílu, zatímco ti, kteří jsou používaní cestách či v karavanách, jsou "
Tak dlouho jsem měnil formulaci, až jsem to pokakal.

2020-10-10 06:32 UTC, celerini approved these changes
díky za opravy

2020-10-10 06:35 UTC, merged