Update wesnoth-ei.po
hrubymar10/wesnoth-cs pull request #17
Opened 2020-10-11 10:33 UTC by MultiSeptim

Oprava chyby ve win condition.

Jo a ty zeměpisné věci bychom mohli doplňovat do konvence českého překladu (viz Štiplavé bažiny).

2020-10-11 23:52 UTC, celerini requested changes
nechal jste tam chybnou poznámku o chybě v originálu

ohledně ustálení překladu - přenesl jsem kousek ze svých poznámek na [web stránku](https://emer.cz/michal/wesnoth.html) a dal tam něco z toho, co už jsme spolu řešili

2020-10-12 08:12 UTC, MultiSeptim commented
Opraveno.

2020-10-12 17:59 UTC, celerini approved these changes
v pořádku, díky

2020-10-12 18:02 UTC, merged

2020-10-12 19:38 UTC, MultiSeptim commented
Já jsem spíš myslel zanést to sem [https://wiki.wesnoth.org/CS:Konvence](url). A vůbec by ta stránka potřebovala aktualizovat.