Update wesnoth-tb.po
hrubymar10/wesnoth-cs pull request #171
Opened 2021-08-27 20:20 UTC by MultiSeptim

Dnes jsem to hrál a některé věci mi přišly mimo.

2021-08-27 20:23 UTC, MultiSeptim commented
Myslel jsem, že to bude rychlovka a nakonec jsem to toho dost zabrousil.

2021-08-28 09:35 UTC, celerini requested changes
Jako paráda, spousta vylepšení, díky.

2021-08-28 09:35 UTC, celerini commented on wesnoth-tb.po
> +"Ale teď to znamená to, že si musíme poradit s tím Mordakem sami."
```suggestion
"Ale teď to znamená, že si musíme poradit s tím Mordakem sami."
```

2021-08-28 09:35 UTC, celerini commented on wesnoth-tb.po
> +"tvého bratra. Ostatní nás ujišťovali, že šedí mágové osvobodí všechny duše, "
V předchozí větě je "tvůj bratr". Přijde mi hladší neukončovat následující větu stejně, ale rozvinout dál (zavraždil).
```suggestion
"že to nebyl tvůj bratr. Předpokládám, že muž, kterého dopadli, tvého bratra "
"zavraždil. Ostatní nás ujišťovali, že šedí mágové osvobodí všechny duše, "
```

2021-08-28 09:35 UTC, celerini commented on wesnoth-tb.po
> +"Tak či onak vniknutím do našich lesů nic nezískáte. Už se víc nepřibližujte "
Když se nepřiblíží, nedojde ke střetu (buď - nebo).
```suggestion
"Tak či onak vniknutím do našich lesů nic nezískáte. Už se víc nepřibližujte, "
```

2021-08-28 09:35 UTC, celerini commented on wesnoth-tb.po
> +"cizí vztáhnul ruku mění situaci. Do sedel a kupředu!"
```suggestion
"cizí vztáhnul ruku, mění situaci. Do sedel a kupředu!"
```

2021-08-28 09:35 UTC, celerini commented on wesnoth-tb.po
> +"Skřeti, kteří s námi přišli, hlídají u bran, a všechny své služebníky "
s tím já mi přijde zřejmější, proč je tam shromažďuj**i** a ne shromažďuj**í**
```suggestion
"Skřeti, kteří s námi přišli, hlídají u bran a já všechny své služebníky "
```

2021-08-28 09:35 UTC, celerini commented on wesnoth-tb.po
> +msgstr "Podívejte co jsem tu našel! Dobrá stovka zlatých."
```suggestion
msgstr "Podívejte, co jsem tu našel! Dobrá stovka zlatých."
```

2021-08-28 09:35 UTC, celerini commented on wesnoth-tb.po
> +"problémů jsem musel čelit téměř podobně strastiplnému usmiřování s mým "
```suggestion
"problémů jsem musel čelit téměř podobně strastiplnému usmiřování se svým "
```

2021-08-28 09:35 UTC, celerini commented on wesnoth-tb.po
> +"Maghre se nachází v mnohem lepším stavu než když jsem tu byl naposledy. "
```suggestion
"Maghre se nachází v mnohem lepším stavu, než když jsem tu byl naposledy. "
```

2021-08-29 19:42 UTC, merged