Update wesnoth-units.po
hrubymar10/wesnoth-cs pull request #20
Opened 2020-10-13 18:37 UTC by MultiSeptim

ke commit f376397

2020-10-13 20:18 UTC, celerini requested changes
Díky za překlady.

Začlenění brání několik málo chyb.

2020-10-13 20:18 UTC, celerini commented on wesnoth-units.po
> +"nekonečných experimentech se svým vybavením, překročí v určitém okamžiku "
```suggestion
"nekonečných experimentech se svým vybavením překročí v určitém okamžiku "
```

2020-10-13 20:18 UTC, celerini commented on wesnoth-units.po
> +"jejich vázáním do jediného kvazi souboje."
kvazi se vztahuje k single, ne k souboji
```suggestion
"jejich zatažením do souboje skoro jako muže proti muži."
```

2020-10-13 20:18 UTC, celerini commented on wesnoth-units.po
> +"do značné opomíjeni na poli slávy a uznání. Když útok pouštních lidí selže a "
```suggestion
"do značné míry opomíjeni na poli slávy a uznání. Když útok pouštních lidí selže a "
```

2020-10-13 20:18 UTC, celerini commented on wesnoth-units.po
> +"vyplísnění, je válečník přijat zpět, přinášejíce si své těžce získané "
jednotné číslo přechodníku
```suggestion
"pozici a nezemřel se zbytkem svých nejmenovaných bratří. Nicméně po menším "
"vyplísnění je válečník přijat zpět, přinášeje si své těžce získané "
```

2020-10-14 05:32 UTC, MultiSeptim commented on wesnoth-units.po
> +"jejich vázáním do jediného kvazi souboje."
No, nepřipadá mi o o tolik lepší, ale budiž.

2020-10-14 12:24 UTC, celerini approved these changes
díky za schválení oprav

2020-10-14 13:00 UTC, merged