Update wesnoth-utbs.po
hrubymar10/wesnoth-cs pull request #209
Opened 2022-03-11 23:30 UTC by MultiSeptim

ke commit b810cc6

2022-03-12 08:21 UTC, celerini requested changes

2022-03-12 08:21 UTC, celerini commented on wesnoth-utbs.po
> +"$ally_unit.name taky nemá rád lidi. Jsou skoupí. Ale dělají skvělé zvuky "
```suggestion
"$ally_unit.name taky nemá rád lidi. Jsou skoupí. Ale dělají skvělé zvuky, "
```

2022-03-12 08:21 UTC, celerini commented on wesnoth-utbs.po
> +"nezahanbí Velkého vůdce. Velký vůdce řekl jdi s Kalehem, a $ally_unit.name "
```suggestion
"nezahanbí Velkého vůdce. Velký vůdce řekl jdi s Kalehem a $ally_unit.name "
```

2022-03-12 08:21 UTC, celerini commented on wesnoth-utbs.po
> +"chránit elfy, a $ally_unit.name splní svůj slib. $ally_unit.name bude "
```suggestion
"Ale $ally_unit.name se nebojí. Velký vůdce řekl $ally_unit.name vést a "
"chránit elfy a $ally_unit.name splní svůj slib. $ally_unit.name bude "
```

2022-03-12 08:21 UTC, celerini commented on wesnoth-utbs.po
> +"Velký vůdce řekl, $ally_unit.name bude sloužit Kalehovi, a $ally_unit.name "
```suggestion
"Velký vůdce řekl $ally_unit.name bude sloužit Kalehovi a $ally_unit.name "
```

2022-03-12 08:21 UTC, celerini commented on wesnoth-utbs.po
> +"$ally_unit.name neví jestli věří rybí paní. Co když chce aby elfové bojovali "
```suggestion
"$ally_unit.name neví, jestli věří rybí paní. Co když chce, aby elfové bojovali "
```

2022-03-12 08:21 UTC, celerini commented on wesnoth-utbs.po
> +"udělá všechno aby ji zničil."
```suggestion
"udělá všechno, aby ji zničil."
```

2022-03-12 08:21 UTC, celerini commented on wesnoth-utbs.po
> +"uchovali. Připomínám si, co říkala Zhul, a čemu všichni věřili, totiž že "
```suggestion
"uchovali. Připomínám si, co říkala Zhul a čemu všichni věřili, totiž že "
```

2022-03-12 08:21 UTC, celerini commented on wesnoth-utbs.po
> +"cesty natolik pěkné místo, že $ally_unit.name neváhal obětovat svůj život, "
```suggestion
"cesty, natolik pěkné místo, že $ally_unit.name neváhal obětovat svůj život, "
```

2022-03-12 08:21 UTC, celerini commented on wesnoth-utbs.po
> +"severozápadních skaliscích několik menších jeskyní. Nebyly tak hluboké, jako "
```suggestion
"severozápadních skaliscích několik menších jeskyní. Nebyly tak hluboké jako "
```

2022-03-12 08:21 UTC, celerini commented on wesnoth-utbs.po
> +"radujíc se z krásy a bohatství našeho nového domova. Poté jsme se dali do "
```suggestion
"úžasném vítězství jsme celé dny slavili, děkujíce Eloh a bohu mořského lidu a "
"radujíce se z krásy a bohatství našeho nového domova. Poté jsme se dali do "
```

2022-03-12 08:21 UTC, celerini commented on wesnoth-utbs.po
> +"ještě kdy uvidím. I já si budu navždy pamatovat jej i jeho druh, a dlouho "
```suggestion
"ještě kdy uvidím. I já si budu navždy pamatovat jej i jeho druh a dlouho "
```

2022-03-12 08:21 UTC, celerini commented on wesnoth-utbs.po
> +"radujíc se z krásy a bohatství našeho nového domova. A poté jsme se dali do "
```suggestion
"úžasném vítězství jsme celé dny slavili, děkujíce Eloh a bohu mořského lidu a "
"radujíce se z krásy a bohatství našeho nového domova. A poté jsme se dali do "
```

2022-03-12 08:21 UTC, celerini commented on wesnoth-utbs.po
> +"ještě kdy uvidím. I já si budu navždy pamatovat jej i jeho druh, a dlouho "
```suggestion
"ještě kdy uvidím. I já si budu navždy pamatovat jej i jeho druh a dlouho "
```

2022-03-12 08:21 UTC, celerini commented on wesnoth-utbs.po
> +"Stále budu vzpomínat i na mého přítelem jménem $ally_unit.name, který zemřel "
```suggestion
"Stále budu vzpomínat i na mého přítele jménem $ally_unit.name, který zemřel "
```

2022-03-12 09:51 UTC, MultiSeptim commented
Obecně ale nejsem nadšen těmito typy změn. Dávat do textů jména jako proměnou vždy komplikuje překlady. Chtěl bych vidět, jak se s tím popasují jazyky, které nepoužívají latinku. To bude jako v textu v azbuce jméno latinkou?

2022-03-13 08:50 UTC, merged

2022-03-13 09:18 UTC, celerini commented
Možná by stálo za to, dát vědět autorovi této [změny](https://github.com/wesnoth/wesnoth/issues/6158) a zeptat se přímo něj. Já už to zkoušel vysvětlovat [jinde](https://github.com/hrubymar10/wesnoth-cs/issues/170#issuecomment-903303312).

2022-03-13 11:36 UTC, Wedge009 commented
What's the issue here? With respect to #6165, which involved @stevecotton, @CelticMinstrel, and myself, the intention was simply to remove the redundant duplication of strings. However simple it might be translate duplicate strings, I think it best to avoid them in the source for similar reasons that we avoid redundant duplication in code. Is the issue solely to do with variables that are included within the translated text or is it something more?

2022-03-13 12:18 UTC, MultiSeptim commented
Yes it does. Strings with variables may be difficult to translate.
I reacted to the latest changes in UtBS (main). I dealt with them, but it wasn't easy. Somewhere I had to omit those names from the translation, for example, I used phrase _a dwarf/troll friend_ instead of $ally_unit.name.
I agre that code should be clean. But I haven't registered that $ally_unit.name could be varied somewhere yet (e.g. due to declension).

2022-03-13 14:21 UTC, Wedge009 commented
If I recall correctly, it can be tricky for troll speech because in English speaking in the third person can be interpreted as a sign of low intelligence, and trolls are often characterised this way. Hence sentences like 'Grog promised to help little dwarves' - but 'Grog' is just replaced with the variable name instead (because the troll could be replaced with one of another name).

I'm neither a linguist nor multi-lingual, so pardon me for not fully understanding but is there something more complex to consider than just substituting names for the variable names when reading the lines for localisation? I should add that this isn't a problem unique to the refactoring - it could potentially be present in other campaigns where variables are used.

2022-03-13 15:41 UTC, MultiSeptim commented
It's not so "complicated", it's just how to handle variables well for translation. And yes, this is a very general problem. We came across it, for example, in [.](https://github.com/wesnoth/wesnoth/issues/5114).

2022-03-13 19:08 UTC, celerini commented
We (Czech) are changing (mainly by adding a suffix) nouns (adjectives, pronouns...) according to their gender, grammatical paradigm (pattern, type) and grammatical case (context). Although the case (context) is known from surrounding text, both the gender and the paradigm is not known when using variables. So we can't append the correct suffix to the variable and thus all such translations looks dumb as if it would be a troll speach.

English is simpler than Czech (thus you can deduplicate a text in same manner as a code), but has its own remains of the grammatical case. Consider **he** - I see **he** (not **him**) may look similar in English as when we use a plain variable name in Czech.

I think it can be overcome by using generators, but not for a sake of simplicity. Please se [my previous comment](https://github.com/hrubymar10/wesnoth-cs/issues/170#issuecomment-903303312).

Is it more clear now?

2022-03-13 21:36 UTC, Wedge009 commented
For the specific case of UtBS, where these dwarf and troll allies are concerned, they are always male.

2022-03-13 22:43 UTC, CelticMinstrel commented
I get the issue. It's easy to forget that nouns (even proper nouns) decline in some languages, and I don't even have the excuse of not being a linguist or multilingual. Although it's unfortunate, given the effort @Wedge009 and I put into that pull request, the simplest solution to this problem is likely to just revert it. Looking at it, as far as I can tell it didn't include any other changes beyond the string deduplication.

That said, this pull request (which seems unrelated?) probably isn't the best place to discuss it. I might've missed the whole conversation if I hadn't misclicked my notifications.

2022-03-13 22:48 UTC, MultiSeptim commented
In the first example, the name is in the fifth case. So variable will not work properly.
In the second example, the name is in the first case. So variable could work, except the situation when we translate the name also (like Conrad -> Konrád).

2022-03-13 22:51 UTC, Wedge009 commented
> That said, this pull request (which seems unrelated?) probably isn't the best place to discuss it. I might've missed the whole conversation if I hadn't misclicked my notifications.

I replied here, because the question was put to me directly in the Wesnoth issue report (not the PR) relating to the text consolidation. Are you saying that you're in favour of reverting that work? I'm uncomfortable with having all that duplication for the reasons we worked on the PR in the first place, plus I was reviewing the changes to see if po hints could be added to assist.

> In the first example, the name is in the fifth case. So variable will not work properly. In the second example, the name is in the first case. So variable could work (male and female too), except the situation when we translate the name also (like Conrad -> Konrád).

I appreciate that. The point of the examples I listed was to point out that the challenges you're facing with variables is a general translation difficulty, not specific to the UtBS consolidation we did.

2022-03-13 23:10 UTC, CelticMinstrel commented
> In the first example, the name (noun) is in the fifth case. So variable will not work properly.
> In the second example, the name (noun) is in the first case. So variable could work (male and female too), except the situation when we translate the name also (like Conrad -> Konrád).

Even if that's true for one language, I don't think I can guarantee it's true for every supported language.

> Are you saying that you're in favour of reverting that work? I'm uncomfortable with having all that duplication for the reasons we worked on the PR in the first place, plus I was reviewing the changes to see if po hints could be added to assist.

I don't like seeing duplication either, but as this exact issue shows, deduplication can hurt localization. I think a localization system could theoretically be made that handles this automatically, but gettext is not that (and I don't believe one exists), so unless you can come up with a better idea, then… yes, I am reluctantly in favour of reverting it.

2022-03-14 00:32 UTC, Wedge009 commented
Have reverted the text consolidation and re-opened the associated issue.

2022-03-14 03:16 UTC, CelticMinstrel commented
The associated issue is wesnoth/wesnoth#6158.