Update wesnoth-wof.po
hrubymar10/wesnoth-cs pull request #218
Opened 2022-05-22 19:39 UTC by MultiSeptim

2022-05-23 18:44 UTC, celerini requested changes

2022-05-23 18:44 UTC, celerini commented on wesnoth-wof.po
> +"jejich malou tonáž.\n"
```suggestion
"Pevná a spolehlivá karavela je stěžejním prostředkem lidského "
"průzkumu oceánu, lodní přepravy a rozšiřování vlivu. Je lépe uzpůsobená "
"plavbě po moři než lehčí plavidla, přesto může být spatřena při plavbě na "
"hlubších řekách, kde manévrovací schopnosti a mělký ponor poněkud kompenzují "
"její tonáž.\n"
```

2022-05-23 18:44 UTC, celerini commented on wesnoth-wof.po
> +"což je činí schopnými se bránit pirátům i mořským příšerám.\n"
```suggestion
"Její skromná rychlost v porovnání s plavidly jiných ras jí sice ztěžuje "
"únik, ale její vysoké přední a zadní paluby obsahují mocný arzenál balist, "
"což ji činí schopnou se bránit pirátům i mořským příšerám.\n"
```

2022-05-23 18:44 UTC, celerini commented on wesnoth-wof.po
> +"zranitelné."
```suggestion
"Karavela může zakotvit v pobřežních vesnicích, jakkoli ji to činí zcela "
"zranitelnou."
```

2022-05-23 18:44 UTC, celerini commented on wesnoth-wof.po
> +# Převedeno na množné číslo. Originál zase stojí za prd a nejsem si úplně jistý, co tím chtěl básník říci.
```suggestion
```

2022-05-23 18:44 UTC, celerini commented on wesnoth-wof.po
> +"kmeny skřetů jeho maso považovují za delikatesu.\n"
```suggestion
"kmeny skřetů jeho maso považují za delikatesu.\n"
```

2022-05-23 18:44 UTC, celerini commented on wesnoth-wof.po
> +msgstr "Strážní lodice"
```suggestion
msgstr "Strážná lodice"
```

2022-05-23 18:44 UTC, celerini commented on wesnoth-wof.po
> +"Tyto nájezdná plavidla prořezávají svým nízkým ponorem lehce vodní hladinu a "
```suggestion
"Tato nájezdná plavidla prořezávají svým nízkým ponorem lehce vodní hladinu a "
```

2022-05-23 20:16 UTC, MultiSeptim commented on wesnoth-wof.po
> +"jejich malou tonáž.\n"
Stejně to nedává smysl s tím poněkud kompenzují její tonáž. Jako že se uvažují ještě větší standartní plavidla?

2022-05-23 20:18 UTC, MultiSeptim commented on wesnoth-wof.po
> +# Převedeno na množné číslo. Originál zase stojí za prd a nejsem si úplně jistý, co tím chtěl básník říci.
Popisy jednotek jsou standartně v množném čísle. Očekávám změnu originálu, ale počkám si tedy...

2022-05-24 15:33 UTC, MultiSeptim commented
Klidně slučuj...

2022-05-24 18:39 UTC, celerini commented on wesnoth-wof.po
> +"jejich malou tonáž.\n"
Chápu to jinak, jen jako ospravedlnění toho, že může na řeku, přestože je karavela velká a určená pro moře. A může na řeku díky tomu, že se dá dobře ovládat a má malý ponor. Asi jde o to říct, přes jaké hexy se může posouvat (mělká voda? - nevím, nehrál jsem).

2022-05-24 18:43 UTC, merged