Update wesnoth-wof.po
hrubymar10/wesnoth-cs pull request #245
Opened 2023-03-12 19:44 UTC by MultiSeptim

ke commit d323125

2023-03-14 22:01 UTC, celerini requested changes
Díky, je toho dost.

2023-03-14 22:01 UTC, celerini commented on wesnoth-wof.po
> +"Dokud nás nepřekvapí porážka stejně jako před námi překvapila vládce "
```suggestion
"Dokud nás nepřekvapí porážka, stejně jako před námi překvapila vládce "
```

2023-03-14 22:01 UTC, celerini commented on wesnoth-wof.po
> +"Můj lov byl vskutku ukončen a to neúspěchem.\n"
```suggestion
"Můj lov byl vskutku ukončen, a to neúspěchem.\n"
```

2023-03-14 22:01 UTC, celerini commented on wesnoth-wof.po
> +"Jsme daleko od Morogoru.\n"
Tak Morogoru, nebo Morogora? Jsem zmaten.

2023-03-14 22:01 UTC, celerini commented on wesnoth-wof.po
> +"Přesto tam chyběly i spalovači.\n"
```suggestion
"Přesto tam chyběli i spalovači.\n"
```

2023-03-14 22:01 UTC, celerini commented on wesnoth-wof.po
> +"radu shromážděnou vysoko na jeho Slunných vrcholcích. Tam jim osvětlil novou "
```suggestion
"radu shromážděnou vysoko na svých Slunných vrcholcích. Tam jim osvětlil novou "
```

2023-03-15 11:44 UTC, MultiSeptim commented on wesnoth-wof.po
> +"Jsme daleko od Morogoru.\n"
To je trochu oříšek. Morogor byl ten vůdce (vládce) drakonidů, který je přivedl na to souostroví. Myslím, že je o tom kampaň Flight to Freedom. To souostroví, nový domov drakonidů, se začal nazývat po něm. A ty pravidla (Cesty), jsou vlastně ustanoveny osobou Morogor (již nežijící), ale zároveň se staly i Cestami Morogoru jako území.
Sám mám problém někdy rozklíčovat, jak to správně přeložit. Protože originál je (asi i úmyslně) trochu dvojznačný.

2023-03-15 11:46 UTC, MultiSeptim commented on wesnoth-wof.po
> +"Jsme daleko od Morogoru.\n"
V tomto případě je ta vzdálenost spíše určením fyzické vzdálenosti, než vzdálenosti duchovní. Takže jsem se přiklonil k výkladu, že jde o to souostroví.

2023-03-16 19:49 UTC, merged