Update wesnoth-ei.po
hrubymar10/wesnoth-cs pull request #276
Opened 2023-12-17 16:46 UTC by MultiSeptim

2023-12-17 18:37 UTC, celerini requested changes
Dík za další příspěvky.

Já dopižlal WoFko a teď bych mohl začít oždibovat EI - můžeme na tom dělat spolu, když si nepolezeme do zelí. Vzal bych si fuzzy s jejich bezprostředním okolím, ale všiml jsem si, že sis jich pár přidal jako poznámky nedodělků, takže by bylo asi lepší nechat tě je dokončit. Taky mne baví achievements, ale ty už máš skoro hotové.

Takže jestli máš nějaký nápad, na čem bych mohl pomalu dělat, abych tě nerušil a nezdržoval, dej vědět.

2023-12-17 18:37 UTC, celerini commented on wesnoth-ei.po
> +"loajálního, hrdého a přesto moudrého. Ale především se Dacyn snažil jednat "
```suggestion
"loajálního, hrdého, a přesto moudrého. Ale především se Dacyn snažil jednat "
```

2023-12-17 18:37 UTC, celerini commented on wesnoth-ei.po
>  msgid "Recruit the dunefolk in ‘<i>Ill Humours</i>’."
```suggestion
#, fuzzy
msgid "Recruit the dunefolk in ‘<i>Ill Humours</i>’."
```

2023-12-18 21:35 UTC, MultiSeptim commented
No, kdybys přeložil všechny názvy scénářů a dodělal ty achievements, tak by to bylo fajn. A klidně i všechny ty předměty na konci katalogu.

2023-12-18 22:12 UTC, merged

2023-12-21 19:32 UTC, celerini commented
Tak jsem pojmenoval zbytek scénářů. Neboj se mít rozpracovanou starší verzi, tvoje dílo by mělo jít sloučit s tím mým, dokud se nestrefíme do stejné zprávy.