Update wesnoth-wc.po
hrubymar10/wesnoth-cs pull request #42
Opened 2020-10-28 13:35 UTC by MultiSeptim

ke commit 2e97754
Malý pokus...

2020-10-28 21:19 UTC, celerini requested changes
přispívám svou troškou

2020-10-28 21:19 UTC, celerini commented on wesnoth-wc.po
> +msgstr " scénář:"
```suggestion
msgstr " scénář: "
```

2020-10-28 21:19 UTC, celerini commented on wesnoth-wc.po
> +msgstr " mapa:"
```suggestion
msgstr " mapa: "
```

2020-10-28 21:19 UTC, celerini commented on wesnoth-wc.po
> +"Tento úžasný drahokam umožňuje nositeli dýchat a pohybovat se vodou, výrazně "
```suggestion
"Tento úžasný drahokam umožňuje nositeli dýchat a pohybovat se pod vodou, výrazně "
```

2020-10-28 21:19 UTC, celerini commented on wesnoth-wc.po
> +"ze svých protovníků životní sílu."
```suggestion
"ze svých obětí životní sílu."
```

2020-10-28 21:19 UTC, celerini commented on wesnoth-wc.po
> +"Tato nesvatá příručka poskytuje uživateli tajemné znalosti, využitelné ke "
```suggestion
"Tato nesvatá příručka poskytuje uživateli tajemné znalosti využitelné ke "
```

2020-10-28 21:19 UTC, celerini commented on wesnoth-wc.po
> +"proniknuty ohnivou silou a změní se jejich typ poškození. Zlepšuje také "
```suggestion
"prodchnuty ohnivou silou a změní se jejich typ poškození. Zlepšuje také "
```

2020-10-28 21:19 UTC, celerini commented on wesnoth-wc.po
> +"proniknuty ledovým chladem a změní se jejich typ poškození. Také způsobí "
```suggestion
"prodchnuty ledovým chladem a změní se jejich typ poškození. Také způsobí "
```

2020-10-28 21:19 UTC, celerini commented on wesnoth-wc.po
> +"zasženému nepříteli smrtelné zimnice, které ho zpomalí."
```suggestion
"zasaženému nepříteli smrtelné zimnice, které ho zpomalí."
```

2020-10-28 21:19 UTC, celerini commented on wesnoth-wc.po
> +"zblízka ji posvětí tajemnou silou. Útoky zbraní pak způsobí vyšší poškození "
```suggestion
"zblízka tuto zbraň posvětí tajemnou silou. Útoky zbraní pak způsobí vyšší poškození "
```

2020-10-28 21:42 UTC, MultiSeptim commented on wesnoth-wc.po
> +"ze svých protovníků životní sílu."
Vím, že je tam obětí, ale chtěl jsem použít protivníků (a i to jsem pokakal). Jde mi o to, že si myslíš, že je někdy vhodnější mechaniku hry (nebo tedy konkrétně artefaktu) popisovat neutrálnějším, méně hodnotícím způsobem. Neboť nositel prstenu nemusí být žádný „pachatel“ a ten, s kterým bojuje (a vysává mu život) žádná „oběť“. Jsou to prostě protivníci.

2020-10-28 21:43 UTC, MultiSeptim commented on wesnoth-wc.po
> +"proniknuty ohnivou silou a změní se jejich typ poškození. Zlepšuje také "
To je to slovo!

2020-10-29 19:29 UTC, celerini commented on wesnoth-wc.po
> +"ze svých protovníků životní sílu."
Neutralita mi nevadí. Svezl jsem se očima z chyby na originál a dal svůj návrh. Opravte to podle svého.

2020-10-29 21:57 UTC, merged