Update wesnoth-wc.po
hrubymar10/wesnoth-cs pull request #69
Opened 2020-11-24 23:00 UTC by MultiSeptim

ke commit 77ac227
Trochu jsem si hrál. Ale mám pocit, že mi hra nechce u tohodle český překlad brát. Ale ještě to budu studovat.

2020-11-24 23:04 UTC, MultiSeptim commented
Jo ono to hlásí, že to nefuguje správně kvůli nějakému issue.

2020-11-25 16:49 UTC, celerini requested changes
Mně hra dosavadní překlad WC ukazuje.

[Issue](https://github.com/wesnoth/wesnoth/issues/4801) se má týkat jen verzí 1.15.2 a 1.15.3 a jen okna Invest při verbování jednotky. Tedy mně teď verze 1.15.16 při investování hází chybu. Ale tato chyba ani issue 4801 s ukazováním českého překladu nesouvisí.

2020-11-25 16:49 UTC, celerini commented on wesnoth-wc.po
> +msgstr "spousedící spojenecké jednotky způsobují o 20 % vyšší poškození"
```suggestion
msgstr "sousedící spojenecké jednotky způsobují o 20 % vyšší poškození"
```

2020-11-25 16:49 UTC, celerini commented on wesnoth-wc.po
> +msgstr "let"
nevím, kam to patří, přesto si dovoluji navrhnout
```suggestion
msgstr "létání"
```

2020-11-25 16:53 UTC, MultiSeptim commented
Budu dál zkoušet.

2020-11-25 17:00 UTC, merged